<?php
/**
 * Auto generated by PRADO - WSAT on 2021-11-09 06:29:37.
 * @author 
 */
class AR_TPublicaciones extends TActiveRecord
{
	const TABLE='t_publicaciones';

	public $publica_id;
	public $publica_titulo;
	public $publica_descripcion;
	public $publica_fechacreacion;
	public $usuario_id;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		't_usuario' => array(self::BELONGS_TO, 'AR_TUsuario', 'usuario_id')
	);

	public function __toString() {
		return $this->publica_titulo;
	}
}