<?php
/**
 * Auto generated by PRADO - WSAT on 2021-11-09 06:29:37.
 * @author 
 */
class AR_TUsuario extends TActiveRecord
{
	const TABLE='t_usuario';

	public $usuario_id;
	public $usuario_nombre;
	public $usuario_correo;
	public $usuario_password;
	public $usuario_edad;
	public $tipusu_id;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		't_tipousuario' => array(self::BELONGS_TO, 'AR_TTipousuario', 'tipusu_id'),
		't_publicaciones' => array(self::HAS_MANY, 'AR_TPublicaciones', 'usuario_id')
	);

	public function __toString() {
		return $this->usuario_nombre;
	}
}