<?php
/**
 * Auto generated by PRADO - WSAT on 2021-11-09 06:29:37.
 * @author 
 */
class AR_TTipousuario extends TActiveRecord
{
	const TABLE='t_tipousuario';

	public $tipusu_id;
	public $tipusu_nombre;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		't_usuario' => array(self::HAS_MANY, 'AR_TUsuario', 'tipusu_id')
	);

	public function __toString() {
		return $this->tipusu_nombre;
	}
}